### PR TITLE
alliance-21 updated codebase to reflect new repo/branding

### PR DESCRIPTION
**Pull request by jaymcnallie**
#### What does this PR do?
Update codebase for new branding, refactor package names.
#### Who is reviewing it?
@jlcsmith @kcwire @troymohl @bdeining
#### How should this be tested?
Build against a clean repo.  Extract distro and verify it starts/installs successfully.
#### Any background context you want to provide?
Nope.
#### What are the relevant tickets?
https://github.com/connexta/alliance/issues/21
#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by jlcsmith** [comment]
I'm seeing a few left-over references to codice that should probably be changed.

> ./catalog/nsili/catalog-nsili-endpoint/src/test/java/com/connexta/alliance/nsili/endpoint/TestNsiliLibraryImpl.java:    private static final String TEST_ORGANIZATION = "Codice";
./distribution/sdk/sample-nsili-server/src/main/java/com/connexta/alliance/nsili/mockserver/server/MockWebService.java:    private static final String PRODUCT_RELATIVE_PATH = "/src/main/java/org/codice/alliance/nsili/mockserver/data/product.jpg";
./distribution/webconsole-branding-plugin/src/main/java/com/connexta/alliance/distribution/webconsole/branding/AllianceBrandingPlugin.java:        vendorName = props.getProperty("webconsole.vendor.name", "Codice");
./distribution/webconsole-branding-plugin/src/main/java/com/connexta/alliance/distribution/webconsole/branding/AllianceBrandingPlugin.java:        vendorURL = props.getProperty("webconsole.vendor.url", "http://www.codice.org");

**Comment by jlcsmith** [comment]
Built successfully.  However, I am not seeing the install profiles show up correctly.

**Comment by jaymcnallie** [comment]
Addressed comments and made some changes for new doc artifacts upstream.  Confirmed that install profiles are showing up during install after building to a clean repo.

**Comment by peterhuffer** [comment]
Should references in the ./libs path supposed to be update? I still see some in there.

**Comment by jaymcnallie** [comment]
Updated packages in the `libs/..` path

**Pull request merged**
